spring:
  profiles:
    active: dev
  application:
    name: basic

server:
  port: 8080

# 配置swagger
swagger:
  version: 2.0
  groupName: 基础项目
  title: 基础项目
  description: base 接口文档
  # 扫描的包路径
  basePackage: com.sunskblue.basicserver.controller

#日志配置文件
logging:
  config: classpath:logback-spring.xml
log:
  dir: ./log_data/server_log/
thirdparty:
  log:
    level: ERROR