
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testsql?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver